# Generated by Django 5.1 on 2024-08-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_education_end_year_alter_experience_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
