# Generated by Django 5.1 on 2024-08-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_education_end_year_alter_experience_end_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='slug',
        ),
    ]
