# Generated by Django 5.1 on 2024-09-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_profile_image_testimony_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
