# Generated by Django 5.1 on 2024-10-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_link_profile_delete_education_delete_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='client',
            field=models.CharField(max_length=100, verbose_name='client/organisation'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='occupation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='writer',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
